const apiMall = 'https://xiaochengxu.api.wzdd365.com'
const api_ = {
  merchantTable : apiMall + '/shop/table',
  merchantSubscribe : apiMall  + '/shop/subscribe',
  feedback : apiMall + '/feedback',
  catelog : apiMall + '/info/catelog',
  requirement : apiMall + '/info',
  orderCash : apiMall + '/order/cash',
  WXPay : apiMall + '/payment/wx',
  mapCatelog : apiMall + '/map/catelog',
  login : apiMall + '/authorization/miniprogram',
  userFavoriting : apiMall + '/user/favoriting',
  orderFood : apiMall + '/order/food',
  userWallet : apiMall + '/user/balance',
  orderOutsale : apiMall + '/order/outsale',
  orderGood : apiMall + '/order/good',
  subscribe : apiMall + '/shop/subscribe',
  shopCoupon : apiMall + '/shop/coupon',
  userGet_coupon : apiMall + '/user/get_coupon',
  orderKillbuy : apiMall + '/order/killbuy',
  userWallet_ : apiMall + '/user/wallet',
  userQr : apiMall + '/user/qr',
  recharge : apiMall + '/recharge',
  orderWallet : apiMall + '/order/wallet',
  orderGold : apiMall + '/order/gold',
  orderGold_charge : apiMall + '/order/gold_charge',
  userCoupons : apiMall + '/user/coupons',
  cashCoupons : apiMall + '/user/cash_coupons',
  map : apiMall + '/map',
  mapDetail : apiMall + '/map/detail',
  infoPublish : apiMall + '/info/publish',
  orderGroupbuy : apiMall + '/order/groupbuy',
  orderLottery : apiMall + '/order/lottery',
  shopComments : apiMall + '/shop/comments',
  orderRate : apiMall + '/order/rate',
  orderDetail : apiMall + '/order/detail',
  orderSigneds : apiMall + '/order/signed',
  orderTeambuy : apiMall + '/order/teambuy',
  orderJoin_teambuy : apiMall + '/order/join_teambuy',
  orderShare_teambuy : apiMall + '/order/share_teambuy',
  free : apiMall + '/free',
  orderRefuse : apiMall + '/order/refuse',
  appSetting : apiMall + '/app/setting',
  bonus : apiMall + '/bonus',
  bonusBingo : apiMall + '/bonus/bingo',
  userGet_gift : apiMall + '/user/get_gift',
  userGift : apiMall + '/user/gift'
}
module.exports = {
  apiMall,
  api_
}